---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alloy-api-hpa
  namespace: production
  labels:
    app: alloy-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alloy-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 1000
  - type: Pods
    pods:
      metric:
        name: error_rate_percentage
      target:
        type: AverageValue
        averageValue: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alloy-worker-hpa
  namespace: production
  labels:
    app: alloy-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alloy-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 30
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-autoscaling-policies
  namespace: production
data:
  scaling.yaml: |
    # Alloy API Auto-Scaling Policies
    
    # General Configuration
    min_replicas_api: 2
    max_replicas_api: 20
    min_replicas_worker: 1
    max_replicas_worker: 10
    
    # CPU Thresholds
    cpu_scale_up_threshold: 70
    cpu_scale_down_threshold: 40
    cpu_stabilization_window_seconds: 60
    
    # Memory Thresholds
    memory_scale_up_threshold: 80
    memory_scale_down_threshold: 50
    memory_stabilization_window_seconds: 120
    
    # Request Rate Thresholds
    requests_per_second_scale_up: 1000
    requests_per_second_scale_down: 300
    requests_stabilization_window_seconds: 60
    
    # Error Rate Thresholds
    error_rate_scale_up: 5
    error_rate_critical_threshold: 10
    error_rate_stabilization_window_seconds: 120
    
    # Scale Down Policies
    scale_down_cooldown_seconds: 300
    scale_down_percent: 50
    
    # Scale Up Policies
    scale_up_cooldown_seconds: 30
    scale_up_percent: 100
    scale_up_max_pods: 4
    
    # Time-based Scaling
    enable_time_based_scaling: true
    high_traffic_start_hour: 8
    high_traffic_end_hour: 20
    high_traffic_min_replicas: 5
    low_traffic_min_replicas: 2
    
    # Predictive Scaling
    enable_predictive_scaling: false
    prediction_window_minutes: 30
    prediction_threshold_percent: 20
