from __future__ import annotations
from typing import Generic, TypeVar, Optional, Protocol
from pydantic import BaseModel
from app.schemas.pagination import PaginationParams, PaginatedResult

T = TypeVar('T')
ID = TypeVar('ID')

class Repository(Protocol[T, ID]):
    async def get(self, id: ID) -> Optional[T]: ...
    async def list(self, filter: dict, pagination: PaginationParams) -> PaginatedResult[T]: ...
    async def create(self, entity: T) -> T: ...
    async def update(self, id: ID, updates: dict) -> Optional[T]: ...
    async def delete(self, id: ID) -> bool: ...
